packages:
  - './@aibindkit/core'
  - './@aibindkit/express'
  - './@aibindkit/llm'
  - './@aibindkit/react'
  - './shared'
  - './server'
  - './portal'
  - './cli'
  - './bridge/lib'
  - './bridge/server'
